# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from foreman_msg/Command.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Command(genpy.Message):
  _md5sum = "6ea48707806b8e8fa7ee906cce3e1a86"
  _type = "foreman_msg/Command"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Bool preciseMode
std_msgs/Bool eeOrientationMode 
std_msgs/Bool jointMode
std_msgs/Int8 targetJoint
std_msgs/Float32 x
std_msgs/Float32 y
std_msgs/Float32 z
std_msgs/Bool incrementQ
std_msgs/Bool decrementQ
================================================================================
MSG: std_msgs/Bool
bool data
================================================================================
MSG: std_msgs/Int8
int8 data

================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['preciseMode','eeOrientationMode','jointMode','targetJoint','x','y','z','incrementQ','decrementQ']
  _slot_types = ['std_msgs/Bool','std_msgs/Bool','std_msgs/Bool','std_msgs/Int8','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Bool','std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       preciseMode,eeOrientationMode,jointMode,targetJoint,x,y,z,incrementQ,decrementQ

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Command, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.preciseMode is None:
        self.preciseMode = std_msgs.msg.Bool()
      if self.eeOrientationMode is None:
        self.eeOrientationMode = std_msgs.msg.Bool()
      if self.jointMode is None:
        self.jointMode = std_msgs.msg.Bool()
      if self.targetJoint is None:
        self.targetJoint = std_msgs.msg.Int8()
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.z is None:
        self.z = std_msgs.msg.Float32()
      if self.incrementQ is None:
        self.incrementQ = std_msgs.msg.Bool()
      if self.decrementQ is None:
        self.decrementQ = std_msgs.msg.Bool()
    else:
      self.preciseMode = std_msgs.msg.Bool()
      self.eeOrientationMode = std_msgs.msg.Bool()
      self.jointMode = std_msgs.msg.Bool()
      self.targetJoint = std_msgs.msg.Int8()
      self.x = std_msgs.msg.Float32()
      self.y = std_msgs.msg.Float32()
      self.z = std_msgs.msg.Float32()
      self.incrementQ = std_msgs.msg.Bool()
      self.decrementQ = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3Bb3f2B().pack(_x.preciseMode.data, _x.eeOrientationMode.data, _x.jointMode.data, _x.targetJoint.data, _x.x.data, _x.y.data, _x.z.data, _x.incrementQ.data, _x.decrementQ.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.preciseMode is None:
        self.preciseMode = std_msgs.msg.Bool()
      if self.eeOrientationMode is None:
        self.eeOrientationMode = std_msgs.msg.Bool()
      if self.jointMode is None:
        self.jointMode = std_msgs.msg.Bool()
      if self.targetJoint is None:
        self.targetJoint = std_msgs.msg.Int8()
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.z is None:
        self.z = std_msgs.msg.Float32()
      if self.incrementQ is None:
        self.incrementQ = std_msgs.msg.Bool()
      if self.decrementQ is None:
        self.decrementQ = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.preciseMode.data, _x.eeOrientationMode.data, _x.jointMode.data, _x.targetJoint.data, _x.x.data, _x.y.data, _x.z.data, _x.incrementQ.data, _x.decrementQ.data,) = _get_struct_3Bb3f2B().unpack(str[start:end])
      self.preciseMode.data = bool(self.preciseMode.data)
      self.eeOrientationMode.data = bool(self.eeOrientationMode.data)
      self.jointMode.data = bool(self.jointMode.data)
      self.incrementQ.data = bool(self.incrementQ.data)
      self.decrementQ.data = bool(self.decrementQ.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3Bb3f2B().pack(_x.preciseMode.data, _x.eeOrientationMode.data, _x.jointMode.data, _x.targetJoint.data, _x.x.data, _x.y.data, _x.z.data, _x.incrementQ.data, _x.decrementQ.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.preciseMode is None:
        self.preciseMode = std_msgs.msg.Bool()
      if self.eeOrientationMode is None:
        self.eeOrientationMode = std_msgs.msg.Bool()
      if self.jointMode is None:
        self.jointMode = std_msgs.msg.Bool()
      if self.targetJoint is None:
        self.targetJoint = std_msgs.msg.Int8()
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.z is None:
        self.z = std_msgs.msg.Float32()
      if self.incrementQ is None:
        self.incrementQ = std_msgs.msg.Bool()
      if self.decrementQ is None:
        self.decrementQ = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.preciseMode.data, _x.eeOrientationMode.data, _x.jointMode.data, _x.targetJoint.data, _x.x.data, _x.y.data, _x.z.data, _x.incrementQ.data, _x.decrementQ.data,) = _get_struct_3Bb3f2B().unpack(str[start:end])
      self.preciseMode.data = bool(self.preciseMode.data)
      self.eeOrientationMode.data = bool(self.eeOrientationMode.data)
      self.jointMode.data = bool(self.jointMode.data)
      self.incrementQ.data = bool(self.incrementQ.data)
      self.decrementQ.data = bool(self.decrementQ.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3Bb3f2B = None
def _get_struct_3Bb3f2B():
    global _struct_3Bb3f2B
    if _struct_3Bb3f2B is None:
        _struct_3Bb3f2B = struct.Struct("<3Bb3f2B")
    return _struct_3Bb3f2B
