# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from foreman/Command.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Command(genpy.Message):
  _md5sum = "e981757b6982377442dcf4f0b1a85562"
  _type = "foreman/Command"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool preciseMode
bool eeOrientationMode 
bool jointMode
uint32 targetJoint
float32 x
float32 y
float32 z"""
  __slots__ = ['preciseMode','eeOrientationMode','jointMode','targetJoint','x','y','z']
  _slot_types = ['bool','bool','bool','uint32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       preciseMode,eeOrientationMode,jointMode,targetJoint,x,y,z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Command, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.preciseMode is None:
        self.preciseMode = False
      if self.eeOrientationMode is None:
        self.eeOrientationMode = False
      if self.jointMode is None:
        self.jointMode = False
      if self.targetJoint is None:
        self.targetJoint = 0
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
    else:
      self.preciseMode = False
      self.eeOrientationMode = False
      self.jointMode = False
      self.targetJoint = 0
      self.x = 0.
      self.y = 0.
      self.z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3BI3f().pack(_x.preciseMode, _x.eeOrientationMode, _x.jointMode, _x.targetJoint, _x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.preciseMode, _x.eeOrientationMode, _x.jointMode, _x.targetJoint, _x.x, _x.y, _x.z,) = _get_struct_3BI3f().unpack(str[start:end])
      self.preciseMode = bool(self.preciseMode)
      self.eeOrientationMode = bool(self.eeOrientationMode)
      self.jointMode = bool(self.jointMode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3BI3f().pack(_x.preciseMode, _x.eeOrientationMode, _x.jointMode, _x.targetJoint, _x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 19
      (_x.preciseMode, _x.eeOrientationMode, _x.jointMode, _x.targetJoint, _x.x, _x.y, _x.z,) = _get_struct_3BI3f().unpack(str[start:end])
      self.preciseMode = bool(self.preciseMode)
      self.eeOrientationMode = bool(self.eeOrientationMode)
      self.jointMode = bool(self.jointMode)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3BI3f = None
def _get_struct_3BI3f():
    global _struct_3BI3f
    if _struct_3BI3f is None:
        _struct_3BI3f = struct.Struct("<3BI3f")
    return _struct_3BI3f
